package arabic

// Letters contains all 28 core Modern Standard Arabic alphabet letters.
var Letters = []Letter{
	{
		ID:           1,
		ArabicName:   "أَلِف",
		EnglishName:  "Alif",
		Translit:     "ā / ʾ",
		IPA:          "/aː/ or /ʔ/",
		SoundDesc:    "Long 'aa' vowel, or glottal carrier when bearing Hamza",
		Forms:        PositionalForms{Isolated: "ا", Initial: "ا", Medial: "ـا", Final: "ـا"},
		IsConnector:  false,
		IsSunLetter:  false,
		Emphatic:     false,
		Confusable:   []int{23},
		PedGroup:     1,
		GroupName:    "The Anchors & Boat Letters",
		Tips:         "A tall straight vertical stroke. Does NOT connect to the letter following it.",
		Examples: []ExampleWord{
			{Arabic: "أَب", Translit: "ʾab", Meaning: "Father", Position: "initial", Highlight: "أ"},
			{Arabic: "كِتَاب", Translit: "kitāb", Meaning: "Book", Position: "medial", Highlight: "ـا"},
			{Arabic: "شَفَا", Translit: "shafā", Meaning: "Edge/Cure", Position: "final", Highlight: "ـا"},
		},
	},
	{
		ID:           2,
		ArabicName:   "بَاء",
		EnglishName:  "Baa",
		Translit:     "b",
		IPA:          "/b/",
		SoundDesc:    "Voiced bilabial stop, identical to English 'b' in 'book'",
		Forms:        PositionalForms{Isolated: "ب", Initial: "بـ", Medial: "ـبـ", Final: "ـب"},
		IsConnector:  true,
		IsSunLetter:  false,
		Emphatic:     false,
		Confusable:   []int{3, 4, 25, 28},
		PedGroup:     1,
		GroupName:    "The Anchors & Boat Letters",
		Tips:         "Wide boat shape with ONE dot BELOW the hull.",
		Examples: []ExampleWord{
			{Arabic: "بَاب", Translit: "bāb", Meaning: "Door", Position: "initial", Highlight: "بـ"},
			{Arabic: "خُبْز", Translit: "khubz", Meaning: "Bread", Position: "medial", Highlight: "ـبـ"},
			{Arabic: "كَلْب", Translit: "kalb", Meaning: "Dog", Position: "final", Highlight: "ـب"},
		},
	},
	{
		ID:           3,
		ArabicName:   "تَاء",
		EnglishName:  "Taa",
		Translit:     "t",
		IPA:          "/t/",
		SoundDesc:    "Voiceless dental stop, like English 't' in 'table' (soft, un-emphatic)",
		Forms:        PositionalForms{Isolated: "ت", Initial: "تـ", Medial: "ـتـ", Final: "ـت"},
		IsConnector:  true,
		IsSunLetter:  true,
		Emphatic:     false,
		Confusable:   []int{2, 4, 16},
		PedGroup:     1,
		GroupName:    "The Anchors & Boat Letters",
		Tips:         "Boat shape with TWO dots ABOVE (like two eyes smiling).",
		Examples: []ExampleWord{
			{Arabic: "تَمْر", Translit: "tamr", Meaning: "Dates (fruit)", Position: "initial", Highlight: "تـ"},
			{Arabic: "كِتَاب", Translit: "kitāb", Meaning: "Book", Position: "medial", Highlight: "ـتـ"},
			{Arabic: "بَيْت", Translit: "bayt", Meaning: "House", Position: "final", Highlight: "ـت"},
		},
	},
	{
		ID:           4,
		ArabicName:   "ثَاء",
		EnglishName:  "Thaa",
		Translit:     "th",
		IPA:          "/θ/",
		SoundDesc:    "Voiceless dental fricative, like 'th' in English 'think' or 'three'",
		Forms:        PositionalForms{Isolated: "ث", Initial: "ثـ", Medial: "ـثـ", Final: "ـث"},
		IsConnector:  true,
		IsSunLetter:  true,
		Emphatic:     false,
		Confusable:   []int{2, 3, 9},
		PedGroup:     1,
		GroupName:    "The Anchors & Boat Letters",
		Tips:         "Boat shape with THREE dots ABOVE forming a triangle (Three = Thaa).",
		Examples: []ExampleWord{
			{Arabic: "ثَوْب", Translit: "thawb", Meaning: "Dress / Robe", Position: "initial", Highlight: "ثـ"},
			{Arabic: "مِثَال", Translit: "mithāl", Meaning: "Example", Position: "medial", Highlight: "ـثـ"},
			{Arabic: "بَحْث", Translit: "baḥth", Meaning: "Research", Position: "final", Highlight: "ـث"},
		},
	},
	{
		ID:           5,
		ArabicName:   "جِيم",
		EnglishName:  "Jeem",
		Translit:     "j",
		IPA:          "/d͡ʒ/ or /ʒ/",
		SoundDesc:    "Voiced postalveolar affricate, like 'j' in 'jam'",
		Forms:        PositionalForms{Isolated: "ج", Initial: "جـ", Medial: "ـجـ", Final: "ـج"},
		IsConnector:  true,
		IsSunLetter:  false,
		Emphatic:     false,
		Confusable:   []int{6, 7},
		PedGroup:     2,
		GroupName:    "The Belly Loopers",
		Tips:         "Hook head with a deep belly; ONE dot inside the belly (below line when initial/medial).",
		Examples: []ExampleWord{
			{Arabic: "جَبَل", Translit: "jabal", Meaning: "Mountain", Position: "initial", Highlight: "جـ"},
			{Arabic: "نَجْم", Translit: "najm", Meaning: "Star", Position: "medial", Highlight: "ـجـ"},
			{Arabic: "ثَلْج", Translit: "thalj", Meaning: "Snow", Position: "final", Highlight: "ـج"},
		},
	},
	{
		ID:           6,
		ArabicName:   "حَاء",
		EnglishName:  "Haa (Pharyngeal)",
		Translit:     "ḥ",
		IPA:          "/ħ/",
		SoundDesc:    "Voiceless pharyngeal fricative: rasping 'h' produced deep in the throat, like breathing on glass",
		Forms:        PositionalForms{Isolated: "ح", Initial: "حـ", Medial: "ـحـ", Final: "ـح"},
		IsConnector:  true,
		IsSunLetter:  false,
		Emphatic:     false,
		Confusable:   []int{5, 7, 26},
		PedGroup:     2,
		GroupName:    "The Belly Loopers",
		Tips:         "Belly shape with NO dots at all (bare, rasping throat sound).",
		Examples: []ExampleWord{
			{Arabic: "حَلِيب", Translit: "ḥalīb", Meaning: "Milk", Position: "initial", Highlight: "حـ"},
			{Arabic: "سَحَاب", Translit: "saḥāb", Meaning: "Clouds", Position: "medial", Highlight: "ـحـ"},
			{Arabic: "صَبَاح", Translit: "ṣabāḥ", Meaning: "Morning", Position: "final", Highlight: "ـح"},
		},
	},
	{
		ID:           7,
		ArabicName:   "خَاء",
		EnglishName:  "Khaa",
		Translit:     "kh",
		IPA:          "/x/",
		SoundDesc:    "Voiceless velar/uvular fricative, like 'ch' in Scottish 'loch' or German 'Bach'",
		Forms:        PositionalForms{Isolated: "خ", Initial: "خـ", Medial: "ـخـ", Final: "ـخ"},
		IsConnector:  true,
		IsSunLetter:  false,
		Emphatic:     false,
		Confusable:   []int{5, 6, 19},
		PedGroup:     2,
		GroupName:    "The Belly Loopers",
		Tips:         "Belly shape with ONE dot ABOVE the head.",
		Examples: []ExampleWord{
			{Arabic: "خُبْز", Translit: "khubz", Meaning: "Bread", Position: "initial", Highlight: "خـ"},
			{Arabic: "نَخْلَة", Translit: "nakhla", Meaning: "Palm tree", Position: "medial", Highlight: "ـخـ"},
			{Arabic: "طَبَّاخ", Translit: "ṭabbākh", Meaning: "Chef / Cook", Position: "final", Highlight: "ـخ"},
		},
	},
	{
		ID:           8,
		ArabicName:   "دَال",
		EnglishName:  "Daal",
		Translit:     "d",
		IPA:          "/d/",
		SoundDesc:    "Voiced dental stop, soft like 'd' in 'door'",
		Forms:        PositionalForms{Isolated: "د", Initial: "د", Medial: "ـد", Final: "ـد"},
		IsConnector:  false,
		IsSunLetter:  true,
		Emphatic:     false,
		Confusable:   []int{9, 15},
		PedGroup:     3,
		GroupName:    "The Short Non-Connectors",
		Tips:         "Small right-angled bend sitting on the line with NO dots. Never connects to the left.",
		Examples: []ExampleWord{
			{Arabic: "دَرْس", Translit: "dars", Meaning: "Lesson", Position: "initial", Highlight: "د"},
			{Arabic: "مَدْرَسَة", Translit: "madrasa", Meaning: "School", Position: "medial", Highlight: "ـد"},
			{Arabic: "وَلَد", Translit: "walad", Meaning: "Boy", Position: "final", Highlight: "ـد"},
		},
	},
	{
		ID:           9,
		ArabicName:   "ذَال",
		EnglishName:  "Dhaal",
		Translit:     "dh",
		IPA:          "/ð/",
		SoundDesc:    "Voiced dental fricative, like 'th' in English 'this', 'that', 'mother'",
		Forms:        PositionalForms{Isolated: "ذ", Initial: "ذ", Medial: "ـذ", Final: "ـذ"},
		IsConnector:  false,
		IsSunLetter:  true,
		Emphatic:     false,
		Confusable:   []int{8, 4, 17},
		PedGroup:     3,
		GroupName:    "The Short Non-Connectors",
		Tips:         "Small angle sitting on the line with ONE dot ABOVE. Non-connector.",
		Examples: []ExampleWord{
			{Arabic: "ذَهَب", Translit: "dhahab", Meaning: "Gold", Position: "initial", Highlight: "ذ"},
			{Arabic: "أُذُن", Translit: "ʾudhun", Meaning: "Ear", Position: "medial", Highlight: "ـذ"},
			{Arabic: "أُسْتَاذ", Translit: "ʾustādh", Meaning: "Professor", Position: "final", Highlight: "ـذ"},
		},
	},
	{
		ID:           10,
		ArabicName:   "رَاء",
		EnglishName:  "Raa",
		Translit:     "r",
		IPA:          "/r/",
		SoundDesc:    "Alveolar trill or tap, rolled 'r' like Spanish 'perro' or Italian 'roma'",
		Forms:        PositionalForms{Isolated: "ر", Initial: "ر", Medial: "ـر", Final: "ـر"},
		IsConnector:  false,
		IsSunLetter:  true,
		Emphatic:     false,
		Confusable:   []int{8, 11},
		PedGroup:     3,
		GroupName:    "The Short Non-Connectors",
		Tips:         "Gentle sweeping crescent dipping below the baseline with NO dots. Non-connector.",
		Examples: []ExampleWord{
			{Arabic: "رَجُل", Translit: "rajul", Meaning: "Man", Position: "initial", Highlight: "ر"},
			{Arabic: "قَرِيب", Translit: "qarīb", Meaning: "Near / Close", Position: "medial", Highlight: "ـر"},
			{Arabic: "قَمَر", Translit: "qamar", Meaning: "Moon", Position: "final", Highlight: "ـر"},
		},
	},
	{
		ID:           11,
		ArabicName:   "زَاي",
		EnglishName:  "Zaay",
		Translit:     "z",
		IPA:          "/z/",
		SoundDesc:    "Voiced alveolar fricative, like 'z' in 'zebra'",
		Forms:        PositionalForms{Isolated: "ز", Initial: "ز", Medial: "ـز", Final: "ـز"},
		IsConnector:  false,
		IsSunLetter:  true,
		Emphatic:     false,
		Confusable:   []int{10, 9},
		PedGroup:     3,
		GroupName:    "The Short Non-Connectors",
		Tips:         "Crescent dipping below baseline with ONE dot ABOVE. Non-connector.",
		Examples: []ExampleWord{
			{Arabic: "زَيْت", Translit: "zayt", Meaning: "Oil", Position: "initial", Highlight: "ز"},
			{Arabic: "مَزْرَعَة", Translit: "mazraʿa", Meaning: "Farm", Position: "medial", Highlight: "ـز"},
			{Arabic: "مَوْز", Translit: "mawz", Meaning: "Banana", Position: "final", Highlight: "ـز"},
		},
	},
	{
		ID:           12,
		ArabicName:   "سِين",
		EnglishName:  "Seen",
		Translit:     "s",
		IPA:          "/s/",
		SoundDesc:    "Voiceless alveolar fricative, sharp soft 's' as in 'sun'",
		Forms:        PositionalForms{Isolated: "س", Initial: "سـ", Medial: "ـسـ", Final: "ـس"},
		IsConnector:  true,
		IsSunLetter:  true,
		Emphatic:     false,
		Confusable:   []int{13, 14},
		PedGroup:     4,
		GroupName:    "The Teeth & Deep Bowls",
		Tips:         "Three small teeth (w-shape) with NO dots; deep bowl below line when final/isolated.",
		Examples: []ExampleWord{
			{Arabic: "سَمَك", Translit: "samak", Meaning: "Fish", Position: "initial", Highlight: "سـ"},
			{Arabic: "مَسْجِد", Translit: "masjid", Meaning: "Mosque", Position: "medial", Highlight: "ـسـ"},
			{Arabic: "شَمْس", Translit: "shams", Meaning: "Sun", Position: "final", Highlight: "ـس"},
		},
	},
	{
		ID:           13,
		ArabicName:   "شِين",
		EnglishName:  "Sheen",
		Translit:     "sh",
		IPA:          "/ʃ/",
		SoundDesc:    "Voiceless postalveolar fricative, like 'sh' in 'shoe'",
		Forms:        PositionalForms{Isolated: "ش", Initial: "شـ", Medial: "ـشـ", Final: "ـش"},
		IsConnector:  true,
		IsSunLetter:  true,
		Emphatic:     false,
		Confusable:   []int{12},
		PedGroup:     4,
		GroupName:    "The Teeth & Deep Bowls",
		Tips:         "Three teeth topped with THREE dots in a triangle pyramid.",
		Examples: []ExampleWord{
			{Arabic: "شَمْس", Translit: "shams", Meaning: "Sun", Position: "initial", Highlight: "شـ"},
			{Arabic: "مَشْي", Translit: "mashy", Meaning: "Walking", Position: "medial", Highlight: "ـشـ"},
			{Arabic: "عَيْش", Translit: "ʿaysh", Meaning: "Life / Bread", Position: "final", Highlight: "ـش"},
		},
	},
	{
		ID:           14,
		ArabicName:   "صَاد",
		EnglishName:  "Saad (Emphatic)",
		Translit:     "ṣ",
		IPA:          "/sˤ/",
		SoundDesc:    "Voiceless alveolar emphatic fricative: heavy, hollow 's' made with back of tongue raised",
		Forms:        PositionalForms{Isolated: "ص", Initial: "صـ", Medial: "ـصـ", Final: "ـص"},
		IsConnector:  true,
		IsSunLetter:  true,
		Emphatic:     true,
		Confusable:   []int{12, 15},
		PedGroup:     4,
		GroupName:    "The Teeth & Deep Bowls",
		Tips:         "Oval teardrop loop with a single trailing tooth and NO dots. Deep emphatic tone.",
		Examples: []ExampleWord{
			{Arabic: "صَبَاح", Translit: "ṣabāḥ", Meaning: "Morning", Position: "initial", Highlight: "صـ"},
			{Arabic: "فَصْل", Translit: "faṣl", Meaning: "Class / Season", Position: "medial", Highlight: "ـصـ"},
			{Arabic: "قَفَص", Translit: "qafaṣ", Meaning: "Cage", Position: "final", Highlight: "ـص"},
		},
	},
	{
		ID:           15,
		ArabicName:   "ضَاد",
		EnglishName:  "Daad (Emphatic)",
		Translit:     "ḍ",
		IPA:          "/dˤ/",
		SoundDesc:    "Voiced alveolar emphatic stop: heavy, deep 'd' (Arabic is called Lughat al-Daad)",
		Forms:        PositionalForms{Isolated: "ض", Initial: "ضـ", Medial: "ـضـ", Final: "ـض"},
		IsConnector:  true,
		IsSunLetter:  true,
		Emphatic:     true,
		Confusable:   []int{8, 14, 17},
		PedGroup:     4,
		GroupName:    "The Teeth & Deep Bowls",
		Tips:         "Oval loop with tooth and ONE dot ABOVE. Heavy, deep sound unique to Arabic.",
		Examples: []ExampleWord{
			{Arabic: "ضَوْء", Translit: "ḍawʾ", Meaning: "Light", Position: "initial", Highlight: "ضـ"},
			{Arabic: "خُضَار", Translit: "khuḍār", Meaning: "Vegetables", Position: "medial", Highlight: "ـضـ"},
			{Arabic: "أَبْيَض", Translit: "ʾabyaḍ", Meaning: "White", Position: "final", Highlight: "ـض"},
		},
	},
	{
		ID:           16,
		ArabicName:   "طَاء",
		EnglishName:  "Taa' (Emphatic)",
		Translit:     "ṭ",
		IPA:          "/tˤ/",
		SoundDesc:    "Voiceless dental emphatic stop: heavy, resonant 't' with throat tightened",
		Forms:        PositionalForms{Isolated: "ط", Initial: "طـ", Medial: "ـطـ", Final: "ـط"},
		IsConnector:  true,
		IsSunLetter:  true,
		Emphatic:     true,
		Confusable:   []int{3, 17},
		PedGroup:     5,
		GroupName:    "The Tall Emphatics & Deep Gutturals",
		Tips:         "Oval loop with a tall vertical mast and NO dots. Fully connects on both sides.",
		Examples: []ExampleWord{
			{Arabic: "طَالِب", Translit: "ṭālib", Meaning: "Student", Position: "initial", Highlight: "طـ"},
			{Arabic: "مَطَار", Translit: "maṭār", Meaning: "Airport", Position: "medial", Highlight: "ـطـ"},
			{Arabic: "قِطّ", Translit: "qiṭṭ", Meaning: "Cat", Position: "final", Highlight: "ـط"},
		},
	},
	{
		ID:           17,
		ArabicName:   "ظَاء",
		EnglishName:  "Dhaa' (Emphatic)",
		Translit:     "ẓ",
		IPA:          "/ðˤ/",
		SoundDesc:    "Voiced dental emphatic fricative: heavy 'th' as in 'the', throat constricted",
		Forms:        PositionalForms{Isolated: "ظ", Initial: "ظـ", Medial: "ـظـ", Final: "ـظ"},
		IsConnector:  true,
		IsSunLetter:  true,
		Emphatic:     true,
		Confusable:   []int{9, 16},
		PedGroup:     5,
		GroupName:    "The Tall Emphatics & Deep Gutturals",
		Tips:         "Oval loop with a tall vertical mast plus ONE dot ABOVE.",
		Examples: []ExampleWord{
			{Arabic: "ظِلّ", Translit: "ẓill", Meaning: "Shadow", Position: "initial", Highlight: "ظـ"},
			{Arabic: "نَظَّارَة", Translit: "naẓẓāra", Meaning: "Glasses", Position: "medial", Highlight: "ـظـ"},
			{Arabic: "حَفِظَ", Translit: "ḥafiẓa", Meaning: "Memorized / Guarded", Position: "final", Highlight: "ـظ"},
		},
	},
	{
		ID:           18,
		ArabicName:   "عَيْن",
		EnglishName:  "'Ayn",
		Translit:     "ʿ",
		IPA:          "/ʕ/",
		SoundDesc:    "Voiced pharyngeal fricative: deep tightening of vocal cords, quintessential Arabic sound",
		Forms:        PositionalForms{Isolated: "ع", Initial: "عـ", Medial: "ـعـ", Final: "ـع"},
		IsConnector:  true,
		IsSunLetter:  false,
		Emphatic:     false,
		Confusable:   []int{19, 1},
		PedGroup:     5,
		GroupName:    "The Tall Emphatics & Deep Gutturals",
		Tips:         "Crescent open to right. In medial (ـعـ) and final (ـع) forms, the head loops closed like a triangle!",
		Examples: []ExampleWord{
			{Arabic: "عَيْن", Translit: "ʿayn", Meaning: "Eye / Spring", Position: "initial", Highlight: "عـ"},
			{Arabic: "مُعَلِّم", Translit: "muʿallim", Meaning: "Teacher", Position: "medial", Highlight: "ـعـ"},
			{Arabic: "شَارِع", Translit: "shāriʿ", Meaning: "Street", Position: "final", Highlight: "ـع"},
		},
	},
	{
		ID:           19,
		ArabicName:   "غَيْن",
		EnglishName:  "Ghayn",
		Translit:     "gh",
		IPA:          "/ɣ/",
		SoundDesc:    "Voiced uvular/velar fricative, like French 'r' in 'Paris' or gentle gargling",
		Forms:        PositionalForms{Isolated: "غ", Initial: "غـ", Medial: "ـغـ", Final: "ـغ"},
		IsConnector:  true,
		IsSunLetter:  false,
		Emphatic:     false,
		Confusable:   []int{18, 7},
		PedGroup:     5,
		GroupName:    "The Tall Emphatics & Deep Gutturals",
		Tips:         "Identical shape to 'Ayn, but with ONE dot ABOVE. Closed triangle loop when medial/final.",
		Examples: []ExampleWord{
			{Arabic: "غَابَة", Translit: "ghāba", Meaning: "Forest", Position: "initial", Highlight: "غـ"},
			{Arabic: "صَغِير", Translit: "ṣaghīr", Meaning: "Small", Position: "medial", Highlight: "ـغـ"},
			{Arabic: "دِمَاغ", Translit: "dimāgh", Meaning: "Brain", Position: "final", Highlight: "ـغ"},
		},
	},
	{
		ID:           20,
		ArabicName:   "فَاء",
		EnglishName:  "Faa",
		Translit:     "f",
		IPA:          "/f/",
		SoundDesc:    "Voiceless labiodental fricative, identical to English 'f' in 'father'",
		Forms:        PositionalForms{Isolated: "ف", Initial: "فـ", Medial: "ـفـ", Final: "ـف"},
		IsConnector:  true,
		IsSunLetter:  false,
		Emphatic:     false,
		Confusable:   []int{21},
		PedGroup:     6,
		GroupName:    "The Looped Tails & Hooks",
		Tips:         "Round head on a short neck with a flat boat tail on the line, ONE dot ABOVE.",
		Examples: []ExampleWord{
			{Arabic: "فِيل", Translit: "fīl", Meaning: "Elephant", Position: "initial", Highlight: "فـ"},
			{Arabic: "طِفْل", Translit: "ṭifl", Meaning: "Child", Position: "medial", Highlight: "ـفـ"},
			{Arabic: "صَيْف", Translit: "ṣayf", Meaning: "Summer", Position: "final", Highlight: "ـف"},
		},
	},
	{
		ID:           21,
		ArabicName:   "قَاف",
		EnglishName:  "Qaaf",
		Translit:     "q",
		IPA:          "/q/",
		SoundDesc:    "Voiceless uvular stop: deep 'k' sound produced at the very back of the palate/uvula",
		Forms:        PositionalForms{Isolated: "ق", Initial: "قـ", Medial: "ـقـ", Final: "ـق"},
		IsConnector:  true,
		IsSunLetter:  false,
		Emphatic:     false,
		Confusable:   []int{20, 22},
		PedGroup:     6,
		GroupName:    "The Looped Tails & Hooks",
		Tips:         "Round head with a deep round bowl dipping BELOW the line, TWO dots ABOVE.",
		Examples: []ExampleWord{
			{Arabic: "قَمَر", Translit: "qamar", Meaning: "Moon", Position: "initial", Highlight: "قـ"},
			{Arabic: "حَقِيبَة", Translit: "ḥaqība", Meaning: "Bag / Suitcase", Position: "medial", Highlight: "ـقـ"},
			{Arabic: "سُوق", Translit: "sūq", Meaning: "Market", Position: "final", Highlight: "ـق"},
		},
	},
	{
		ID:           22,
		ArabicName:   "كَاف",
		EnglishName:  "Kaaf",
		Translit:     "k",
		IPA:          "/k/",
		SoundDesc:    "Voiceless velar stop, standard 'k' in 'kite'",
		Forms:        PositionalForms{Isolated: "ك", Initial: "كـ", Medial: "ـكـ", Final: "ـك"},
		IsConnector:  true,
		IsSunLetter:  false,
		Emphatic:     false,
		Confusable:   []int{21, 23},
		PedGroup:     6,
		GroupName:    "The Looped Tails & Hooks",
		Tips:         "Isolated has a small mark inside; Initial and Medial morph into a slanted zigzag (كـ / ـكـ).",
		Examples: []ExampleWord{
			{Arabic: "كِتَاب", Translit: "kitāb", Meaning: "Book", Position: "initial", Highlight: "كـ"},
			{Arabic: "مَكْتَب", Translit: "maktab", Meaning: "Office / Desk", Position: "medial", Highlight: "ـكـ"},
			{Arabic: "مَلِك", Translit: "malik", Meaning: "King", Position: "final", Highlight: "ـك"},
		},
	},
	{
		ID:           23,
		ArabicName:   "لاَم",
		EnglishName:  "Laam",
		Translit:     "l",
		IPA:          "/l/",
		SoundDesc:    "Voiced alveolar lateral approximant, standard clear 'l' as in 'light'",
		Forms:        PositionalForms{Isolated: "ل", Initial: "لـ", Medial: "ـلـ", Final: "ـل"},
		IsConnector:  true,
		IsSunLetter:  true,
		Emphatic:     false,
		Confusable:   []int{1, 22},
		PedGroup:     6,
		GroupName:    "The Looped Tails & Hooks",
		Tips:         "Tall vertical line that CONNECTS to the left (unlike Alif). Final dips below line like a fishhook.",
		Examples: []ExampleWord{
			{Arabic: "لَيْل", Translit: "layl", Meaning: "Night", Position: "initial", Highlight: "لـ"},
			{Arabic: "قَلَم", Translit: "qalam", Meaning: "Pen", Position: "medial", Highlight: "ـلـ"},
			{Arabic: "عَسَل", Translit: "ʿasal", Meaning: "Honey", Position: "final", Highlight: "ـل"},
		},
	},
	{
		ID:           24,
		ArabicName:   "مِيم",
		EnglishName:  "Meem",
		Translit:     "m",
		IPA:          "/m/",
		SoundDesc:    "Voiced bilabial nasal, standard 'm' in 'moon'",
		Forms:        PositionalForms{Isolated: "م", Initial: "مـ", Medial: "ـمـ", Final: "ـم"},
		IsConnector:  true,
		IsSunLetter:  false,
		Emphatic:     false,
		Confusable:   []int{26},
		PedGroup:     7,
		GroupName:    "The Final Flow",
		Tips:         "Small circular loop on the line, with tail plunging downward at the end.",
		Examples: []ExampleWord{
			{Arabic: "مَاء", Translit: "māʾ", Meaning: "Water", Position: "initial", Highlight: "مـ"},
			{Arabic: "سَمَاء", Translit: "samāʾ", Meaning: "Sky", Position: "medial", Highlight: "ـمـ"},
			{Arabic: "قَلَم", Translit: "qalam", Meaning: "Pen", Position: "final", Highlight: "ـم"},
		},
	},
	{
		ID:           25,
		ArabicName:   "نُون",
		EnglishName:  "Noon",
		Translit:     "n",
		IPA:          "/n/",
		SoundDesc:    "Voiced alveolar nasal, standard 'n' in 'noon'",
		Forms:        PositionalForms{Isolated: "ن", Initial: "نـ", Medial: "ـنـ", Final: "ـن"},
		IsConnector:  true,
		IsSunLetter:  true,
		Emphatic:     false,
		Confusable:   []int{2, 3, 4, 28},
		PedGroup:     7,
		GroupName:    "The Final Flow",
		Tips:         "Initial/medial has ONE dot ABOVE. Isolated/final is a deep round bowl dipping below the line.",
		Examples: []ExampleWord{
			{Arabic: "نَهْر", Translit: "nahr", Meaning: "River", Position: "initial", Highlight: "نـ"},
			{Arabic: "بِنْت", Translit: "bint", Meaning: "Girl / Daughter", Position: "medial", Highlight: "ـنـ"},
			{Arabic: "عَيْن", Translit: "ʿayn", Meaning: "Eye", Position: "final", Highlight: "ـن"},
		},
	},
	{
		ID:           26,
		ArabicName:   "هَاء",
		EnglishName:  "Haa (Glottal)",
		Translit:     "h",
		IPA:          "/h/",
		SoundDesc:    "Voiceless glottal fricative, soft effortless 'h' in 'hat' (unlike pharyngeal Haa ح)",
		Forms:        PositionalForms{Isolated: "ه", Initial: "هـ", Medial: "ـهـ", Final: "ـه"},
		IsConnector:  true,
		IsSunLetter:  false,
		Emphatic:     false,
		Confusable:   []int{6, 24},
		PedGroup:     7,
		GroupName:    "The Final Flow",
		Tips:         "Morphs through 4 different looks! Initial has internal loop (هـ), medial has butterfly wings (ـهـ), final is a loop (ـه).",
		Examples: []ExampleWord{
			{Arabic: "هِلاَل", Translit: "hilāl", Meaning: "Crescent", Position: "initial", Highlight: "هـ"},
			{Arabic: "نَهَار", Translit: "nahār", Meaning: "Daytime", Position: "medial", Highlight: "ـهـ"},
			{Arabic: "وَجْه", Translit: "wajh", Meaning: "Face", Position: "final", Highlight: "ـه"},
		},
	},
	{
		ID:           27,
		ArabicName:   "وَاو",
		EnglishName:  "Waaw",
		Translit:     "w / ū",
		IPA:          "/w/ or /uː/",
		SoundDesc:    "Consonantal 'w' in 'wet' or long vowel 'oo' in 'boot'",
		Forms:        PositionalForms{Isolated: "و", Initial: "و", Medial: "ـو", Final: "ـو"},
		IsConnector:  false,
		IsSunLetter:  false,
		Emphatic:     false,
		Confusable:   []int{10, 20},
		PedGroup:     7,
		GroupName:    "The Final Flow",
		Tips:         "Circular head on the line sweeping into a tail below. Never connects to the left (Non-connector).",
		Examples: []ExampleWord{
			{Arabic: "وَرْدَة", Translit: "warda", Meaning: "Rose", Position: "initial", Highlight: "و"},
			{Arabic: "نُور", Translit: "nūr", Meaning: "Light", Position: "medial", Highlight: "ـو"},
			{Arabic: "جَرْو", Translit: "jarw", Meaning: "Puppy", Position: "final", Highlight: "ـو"},
		},
	},
	{
		ID:           28,
		ArabicName:   "يَاء",
		EnglishName:  "Yaa",
		Translit:     "y / ī",
		IPA:          "/j/ or /iː/",
		SoundDesc:    "Consonantal 'y' in 'yes' or long vowel 'ee' in 'seed'",
		Forms:        PositionalForms{Isolated: "ي", Initial: "يـ", Medial: "ـيـ", Final: "ـي"},
		IsConnector:  true,
		IsSunLetter:  false,
		Emphatic:     false,
		Confusable:   []int{2, 3, 25},
		PedGroup:     7,
		GroupName:    "The Final Flow",
		Tips:         "Initial/medial has TWO dots BELOW. Isolated/final resembles a swimming swan dipping below the line.",
		Examples: []ExampleWord{
			{Arabic: "يَد", Translit: "yad", Meaning: "Hand", Position: "initial", Highlight: "يـ"},
			{Arabic: "بَيْت", Translit: "bayt", Meaning: "House", Position: "medial", Highlight: "ـيـ"},
			{Arabic: "شَاي", Translit: "shāy", Meaning: "Tea", Position: "final", Highlight: "ـي"},
		},
	},
}

// AuxiliaryItems contains special characters and short vowel diacritics.
var AuxiliaryItems = []AuxiliaryItem{
	{
		Arabic:      "ء",
		Name:        "Hamza (هَمْزَة)",
		Category:    "Special Character",
		Description: "Glottal stop /ʔ/ sound (like the catch in the throat in 'uh-oh'). Appears alone or seated on Alif (أ, إ), Waaw (ؤ), or Yaa/Nabrah (ئ).",
		Example:     "مَاء (Water) / سُؤَال (Question)",
		Translit:    "ʾ",
	},
	{
		Arabic:      "ة / ـة",
		Name:        "Taa Marbuta (تَاء مَرْبُوطَة)",
		Category:    "Special Character",
		Description: "Tied Taa: marks feminine gender. Pronounced as 'ah' in pause, but pronounced as 'at' when connected in a possessive/construct phrase (Idafa).",
		Example:     "مَدْرَسَة (School) -> madrasah / madrasat",
		Translit:    "h / t",
	},
	{
		Arabic:      "ى / ـى",
		Name:        "Alif Maqsura (أَلِف مَقْصُورَة)",
		Category:    "Special Character",
		Description: "Restricted Alif: looks like a dotless Yaa at the end of words, pronounced as a long /aa/ sound.",
		Example:     "مُسْتَشْفَى (Hospital) / إِلَى (To / Towards)",
		Translit:    "ā",
	},
	{
		Arabic:      "ـَ",
		Name:        "Fatha (فَتْحَة)",
		Category:    "Harakat (Diacritic)",
		Description: "Short vowel mark placed above the consonant, pronounced as short 'a' (like 'u' in 'cup').",
		Example:     "دَرَسَ (darasa - he studied)",
		Translit:    "a",
	},
	{
		Arabic:      "ـُ",
		Name:        "Damma (ضَمَّة)",
		Category:    "Harakat (Diacritic)",
		Description: "Small curled mark placed above the consonant, pronounced as short 'u' (like 'oo' in 'book').",
		Example:     "كُتُب (kutub - books)",
		Translit:    "u",
	},
	{
		Arabic:      "ـِ",
		Name:        "Kasra (كَسْرَة)",
		Category:    "Harakat (Diacritic)",
		Description: "Diagonal stroke placed below the consonant, pronounced as short 'i' (like 'i' in 'bit').",
		Example:     "كِتَاب (kitāb - book)",
		Translit:    "i",
	},
	{
		Arabic:      "ـْ",
		Name:        "Sukun (سُكُون)",
		Category:    "Harakat (Diacritic)",
		Description: "Small circle placed above the consonant indicating the absence of any vowel (a clean consonant stop).",
		Example:     "بِنْت (bint - girl)",
		Translit:    "(no vowel)",
	},
	{
		Arabic:      "ـّ",
		Name:        "Shaddah (شَدَّة)",
		Category:    "Harakat (Diacritic)",
		Description: "Little 'w' shape placed above the letter indicating consonant gemination (holding/doubling the sound).",
		Example:     "مُعَلِّم (muʿallim - teacher)",
		Translit:    "(doubled)",
	},
	{
		Arabic:      "ـً  ـٌ  ـٍ",
		Name:        "Tanween (تَنْوِين)",
		Category:    "Harakat (Diacritic)",
		Description: "Doubled short vowels at word ends indicating indefinite noun case endings: -an (accusative), -un (nominative), -in (genitive).",
		Example:     "شُكْرًا (shukran - thank you)",
		Translit:    "-an, -un, -in",
	},
}

// Stages groups letters into 8 progressive pedagogical learning stages.
var Stages = []Stage{
	{
		Number:      1,
		Name:        "The Anchors & Boat Letters",
		Description: "Master Alif and the single-dot / multi-dot boat letters (Baa, Taa, Thaa).",
		LetterIDs:   []int{1, 2, 3, 4},
	},
	{
		Number:      2,
		Name:        "The Belly Loopers",
		Description: "Jeem, Haa, and Khaa share the identical head and belly body; distinguished solely by dots and throat depth.",
		LetterIDs:   []int{5, 6, 7},
	},
	{
		Number:      3,
		Name:        "The Short Non-Connectors",
		Description: "Daal, Dhaal, Raa, and Zaay never connect to the left, introducing essential cursive rules.",
		LetterIDs:   []int{8, 9, 10, 11},
	},
	{
		Number:      4,
		Name:        "The Teeth & Deep Bowls",
		Description: "Seen, Sheen, and the deep emphatic counterparts Saad and Daad.",
		LetterIDs:   []int{12, 13, 14, 15},
	},
	{
		Number:      5,
		Name:        "The Tall Emphatics & Deep Gutturals",
		Description: "Emphatic Taa' and Dhaa', plus the deep pharyngeal throat letters 'Ayn and Ghayn.",
		LetterIDs:   []int{16, 17, 18, 19},
	},
	{
		Number:      6,
		Name:        "The Looped Tails & Hooks",
		Description: "Faa, Qaaf, Kaaf, and Laam - mastering their cursive morphs and differences.",
		LetterIDs:   []int{20, 21, 22, 23},
	},
	{
		Number:      7,
		Name:        "The Final Flow",
		Description: "Meem, Noon, Haa (the 4-shape chameleon), Waaw, and Yaa.",
		LetterIDs:   []int{24, 25, 26, 27, 28},
	},
	{
		Number:      8,
		Name:        "Auxiliary Characters & Diacritics",
		Description: "Hamza seats, Taa Marbuta, Alif Maqsura, and the essential Harakat short vowels.",
		LetterIDs:   []int{}, // Covers AuxiliaryItems
	},
}

// GetLetterByID returns the Letter with the given ID (1-based) or nil if not found.
func GetLetterByID(id int) *Letter {
	if id >= 1 && id <= len(Letters) {
		return &Letters[id-1]
	}
	return nil
}

// NonConnectingLetters returns the slice of 6 letters that do not connect to the left.
func NonConnectingLetters() []Letter {
	var list []Letter
	for _, l := range Letters {
		if !l.IsConnector {
			list = append(list, l)
		}
	}
	return list
}

// SunLetters returns the 14 Sun (Shamsi) letters.
func SunLetters() []Letter {
	var list []Letter
	for _, l := range Letters {
		if l.IsSunLetter {
			list = append(list, l)
		}
	}
	return list
}

// MoonLetters returns the 14 Moon (Qamari) letters.
func MoonLetters() []Letter {
	var list []Letter
	for _, l := range Letters {
		if !l.IsSunLetter {
			list = append(list, l)
		}
	}
	return list
}
